// Generated by CoffeeScript 1.6.3
(function() {
  app = angular.module("AmqpApp", [])
  app.controller("MainCtrl", function($scope, $http) {
      $scope.dataPush = function(item, event) {

          var responsePromise = $http.get("/data/login?id=" + $scope.data_text);
          //alert($scope.data_box);
          responsePromise.success(function(data, status, headers, config) {
              $scope.state_box = data;
          });
          responsePromise.error(function(data, status, headers, config) {
              $scope.state_box = "test";
              //alert(data);
          });
      };
      $scope.messages = [];
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
